# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zhjIMwSpBhiUvSHn3Y_moExJJribjpHn

String
"""

nama = 'Alisya Harada Yuza'
asal = "Indonesia"

print(nama)

print(asal)

print(nama + asal)

print("Halo, nama saya",nama)

print("Halo, nama saya",nama,"asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""String + Non String"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)