# -*- coding: utf-8 -*-
"""Manipulasi string 3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAujR8Lt2oBw8g6Bp72bdmb9j2wxoEZX

# Nama: Alisya Harada Yuza
# NPM: 2411012039

Format speciflers
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis Febri','Indonesia'))
# output: Halo, saya Lendis Febri dari Indonesia

"""fungsi format ()"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Lendis Febri', asal = 'Indonesia'))
# Halo, sata Lendis Febri dari Indonesia
print(template_2.format('Nasi Goreng', 'air putih'))
# Saya suka makan Nasi Goreng dan minum air putih

"""string interpolation/F-"""

nama = 'Lendis Fabri'
asal = 'Indonesia'

print(f'Perkenalkan saya {nama} dari {asal}')

"""memecahkan string menjadi list dan sebaliknya"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
# ['Surabaya', 'Jawa', 'Timur', 'Indonesia']

print(alamat.split(','))
# ['Surabaya', 'Jawa Timur', 'Indonesia']

print(alamat.split(','))
# ['Surabaya', 'Jawa Timur', 'Indonesia']

print(''.join(['aku', 'suka', 'python']))
# aku suka python

print(''.join(alamat.split(', ')))
# Surabaya Jawa Timur Indonesia

"""mengubah string menjadi upper case"""

print('halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

"""mengubah string menjadi lower case"""

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

"""mengubah string menjadi title case"""

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

"""mengubah string menjadi reverse case"""

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

"""mencari kata pada string"""

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

"""mereplace kata pada string"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', '1'))
print(ibu_kota.replace('kar', ''))
print(ibu_kota.replace('a', ''))

"""menghitung jumlah karakter yang muncul"""

paragraf = 'Baru-baru ini telah ditemukan sebuah melon di suatu sungai'
x = paragraf.count('di')

print(f'kata"di"muncul sebanyak {x} kali')