# -*- coding: utf-8 -*-
"""Pertemuan 4_Alisya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195n97PHNYLs_aKH57N3m4pjLEKn8bnjP

#Nama: Alisya Harada Yuza

#NPM: 2411012039
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input ('Masukan usia anda: ')
print(type(usia))

panjang = int(input('Masukan panjang:'))
lebar = float(input('Masukan lebar:'))

print('Luas =', panjang * lebar)

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Jeruk' * 5

print(kata)
print(type(kata))

panjang = int(input('Masukan panjang: '))
lebar = float(input('Masukan lebar: '))

print('Luas=', panjang * lebar)

nama = 'Wudi'
tahun_lahir = 2000

print(nama + 'lahir di tahun' + str(tahun_lahir))